/**
 * ogentic_redact.h — C FFI shim for the Rust ogentic-redact-core library.
 *
 * This header is the boundary between Rust (compiled to a C-compatible dylib)
 * and the Swift `OgenticRedact` package. It is auto-generated by `cbindgen`
 * during the build; this stub is checked in so the Swift package compiles
 * without requiring a local Rust build.
 *
 * Actual function signatures will be generated once the Rust core API is
 * stabilized (subsequent R* tickets). For F1 only the version query is exposed.
 */

#ifndef OGENTIC_REDACT_H
#define OGENTIC_REDACT_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Returns the library version as a null-terminated UTF-8 string.
 * The caller must NOT free the returned pointer — it points to a
 * static string owned by the Rust runtime.
 */
const char *ogentic_redact_version(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* OGENTIC_REDACT_H */
