/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns the library version string. */
export declare function version(): string
/** The result of a `redact` call. */
export interface RedactResult {
  /** Redacted text with salted placeholder tokens, e.g. `"[Email_3f8a2c1b]"`. */
  text: string
  /** Maps each placeholder to the original value it replaced. */
  tokens: Record<string, string>
}
/**
 * Redact PII in `text` (ADR-0003 grammar `[Label_<salted-hex>]`).
 *
 * Returns `{ text: string, tokens: Record<string, string> }`. Uses a fresh
 * per-call salt, so the same value redacts differently across calls; use
 * `redactWithSalt` for reproducible output.
 */
export declare function redact(text: string): RedactResult
/**
 * Like `redact`, but with an explicit `salt` (bytes) so the salted-hex tokens
 * are reproducible. Surfaces sharing the same salt produce byte-identical
 * output — the basis of the cross-language conformance vectors.
 */
export declare function redactWithSalt(text: string, salt: Buffer): RedactResult
/**
 * Restore redacted placeholders in `text` using the `tokens` map from a prior
 * `redact` call.
 */
export declare function unredact(text: string, tokens: Record<string, string>): string
