/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function version(): string
/** A one-way result. It never contains original values or a reversal map. */
export interface RedactResult {
  text: string
  redactionCount: number
}
export declare function redact(text: string): RedactResult
/** Deterministic one-way output for a caller-supplied salt; never returns PII. */
export declare function redactWithSalt(text: string, salt: Buffer): RedactResult
/** Legacy explicit-map restoration. New reversible callers should use ReversibleRedactor. */
export declare function unredact(text: string, tokens: Record<string, string>, maxOutputBytes?: number, maxReplacements?: number): string
export interface ReversibleResult {
  text: string
  mappingId: string
}
/**
 * Explicit opt-in to reversible redaction. Originals stay in this instance.
 * Call delete() or consume during unredact() when a mapping is no longer needed.
 */
export declare class ReversibleRedactor {
  constructor(maxOutputBytes?: number, maxReplacements?: number)
  redact(text: string): ReversibleResult
  unredact(text: string, mappingId: string, consume?: boolean | undefined | null): string
  delete(mappingId: string): boolean
}
